package org.radargps.localapplication.common.errors;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    ACCESS_DENIED,
    EXCEL_PARSING_FAILED,
    ENTRY_ALREADY_EXISTS,
    INVALID_ARGUMENTS,
    INVALID_PAGINATION_PARAMETERS,
    ALREADY_ASSIGNED,
    ACTIVE_CONNECTION_EXISTS,
    SQL_INTEGRITY_CONSTRAINT_VIOLATION,
    DATA_CONSTRAINT_VIOLATION,
    INVALID_INPUT_FORMAT_EXCEPTION
}
