version: '3.6'

services:
  mysql:
    image: mysql:latest
    container_name: local-app-db
    environment:
      MYSQL_DATABASE: local_application
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3506:3306"
    volumes:
      - /var/lib/mysql/smart-factory:/var/lib/mysql
